import React, { useState } from 'react';
import { Box, Cpu, Gauge, Layers3, MonitorCog, Radio, RotateCcw, SlidersHorizontal, Terminal, Zap } from 'lucide-react';
import { ThreeSimulatorCanvas } from '../simulator/ThreeSimulatorCanvas';
import { MonacoEditorPanel } from '../editor/MonacoEditorPanel';
import { useSimulation } from '../../contexts/SimulationContext';

const PRESETS = {
  rover: { label: 'Autonomous Rover', description: 'Ultrasonic obstacle sensing with virtual rover telemetry.', code: `const int trigPin=11, echoPin=12, ledPin=13;\nvoid setup(){ Serial.begin(9600); pinMode(trigPin,OUTPUT); pinMode(echoPin,INPUT); pinMode(ledPin,OUTPUT); }\nvoid loop(){ long d=readDistance(); Serial.print("Distance: "); Serial.print(d); Serial.println(" cm"); digitalWrite(ledPin,d<20?HIGH:LOW); delay(100); }\nlong readDistance(){ digitalWrite(trigPin,LOW); delayMicroseconds(2); digitalWrite(trigPin,HIGH); delayMicroseconds(10); digitalWrite(trigPin,LOW); return pulseIn(echoPin,HIGH)*0.034/2; }` },
  led: { label: 'LED Telemetry', description: 'Blink GPIO 13 and inspect the virtual serial console.', code: `const int ledPin=13;\nvoid setup(){ Serial.begin(9600); pinMode(ledPin,OUTPUT); }\nvoid loop(){ digitalWrite(ledPin,HIGH); Serial.println("GPIO 13 HIGH"); delay(500); digitalWrite(ledPin,LOW); Serial.println("GPIO 13 LOW"); delay(500); }` },
  servo: { label: 'Servo Sweep', description: 'Test a 180-degree SG90 servo motion profile.', code: `#include <Servo.h>\nServo turret;\nvoid setup(){ Serial.begin(9600); turret.attach(9); }\nvoid loop(){ for(int a=0;a<=180;a+=10){turret.write(a);Serial.println(a);delay(80);} for(int a=180;a>=0;a-=10){turret.write(a);Serial.println(a);delay(80);} }` }
} as const;
type Preset = keyof typeof PRESETS;
const panel='rounded-2xl border border-slate-200/80 bg-white/90 shadow-sm backdrop-blur dark:border-slate-800 dark:bg-slate-950/80';
export const Lab3DWorkbench: React.FC = () => {
  const [preset,setPreset]=useState<Preset>('rover'); const [code,setCode]=useState(PRESETS.rover.code); const [consoleOpen,setConsoleOpen]=useState(true);
  const {state,cameraViewMode,setCameraViewMode,setObstacleDistance,setSpeedMultiplier,resetSimulation,stopSimulation}=useSimulation();
  const choose=(p:Preset)=>{setPreset(p);setCode(PRESETS[p].code);resetSimulation();};
  return <section className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900 dark:bg-[#070b14] dark:text-slate-100 sm:px-5 lg:px-6"><div className="mx-auto max-w-[1800px]">
    <header className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="rounded-xl bg-cyan-500/10 p-3 text-cyan-500"><Box/></div><div><h1 className="text-xl font-black sm:text-2xl">3D Robotics Workbench</h1><p className="text-xs text-slate-500 dark:text-slate-400">Build → code → simulate → inspect virtual hardware.</p></div></div><div className="flex gap-2"><span className="rounded-full border border-slate-200 bg-white px-3 py-2 text-[11px] font-bold dark:border-slate-800 dark:bg-slate-950">{state.isRunning?'RUNNING':state.robot.status}</span><button onClick={stopSimulation} className="rounded-xl border px-3 py-2 text-xs font-bold">Stop</button><button onClick={resetSimulation} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-bold"><RotateCcw className="h-3.5 w-3.5"/>Reset</button></div></header>
    <div className="mb-4 flex gap-2 overflow-x-auto">{(Object.keys(PRESETS) as Preset[]).map(p=><button key={p} onClick={()=>choose(p)} className={`shrink-0 rounded-xl border px-3 py-2 text-xs font-bold ${preset===p?'border-cyan-500 bg-cyan-50 text-cyan-700 dark:bg-cyan-950/50 dark:text-cyan-300':'border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950'}`}>{PRESETS[p].label}</button>)}</div>
    <div className="grid grid-cols-1 gap-4 xl:grid-cols-[230px_minmax(0,1fr)_420px]">
      <aside className={`${panel} p-3`} aria-label="Lab controls"><div className="mb-3 flex items-center gap-2 text-xs font-black uppercase text-slate-500"><SlidersHorizontal className="h-4 w-4"/>Controls</div><div className="space-y-2"><div className="rounded-xl bg-slate-50 p-2.5 dark:bg-slate-900"><div className="flex items-center gap-2 text-xs font-bold"><Cpu className="h-4 w-4 text-cyan-500"/>Arduino Uno R3</div><p className="text-[10px] text-slate-500">ATmega328P · 16 MHz</p></div><div className="rounded-xl bg-slate-50 p-2.5 dark:bg-slate-900"><div className="flex items-center gap-2 text-xs font-bold"><Radio className="h-4 w-4 text-indigo-500"/>HC-SR04</div><p className="text-[10px] text-slate-500">{state.obstacle.distanceToRobot} cm</p></div><div className="rounded-xl bg-slate-50 p-2.5 dark:bg-slate-900"><div className="flex items-center gap-2 text-xs font-bold"><Zap className="h-4 w-4 text-amber-500"/>GPIO 13 LED</div><p className="text-[10px] text-slate-500">{state.leds['13']?.on?'HIGH / ON':'LOW / OFF'}</p></div></div><div className="mt-4 border-t pt-4 dark:border-slate-800"><label className="mb-2 block text-[10px] font-black text-slate-500">CAMERA</label>{([['default','Overview'],['top','Top view'],['rover','Rover focus'],['circuit','Circuit focus']] as const).map(([v,l])=><button key={v} onClick={()=>setCameraViewMode(v)} aria-pressed={cameraViewMode===v} className={`mb-1 flex min-h-10 w-full items-center gap-2 rounded-xl px-3 text-xs font-semibold ${cameraViewMode===v?'bg-cyan-500/10 text-cyan-600':'hover:bg-slate-100 dark:hover:bg-slate-900'}`}><MonitorCog className="h-3.5 w-3.5"/>{l}</button>)}</div><div className="mt-4 border-t pt-4 dark:border-slate-800"><label htmlFor="obstacle" className="mb-2 flex justify-between text-[10px] font-black text-slate-500">Obstacle <span>{state.obstacle.distanceToRobot} cm</span></label><input id="obstacle" type="range" min="5" max="100" value={state.obstacle.distanceToRobot} onChange={e=>setObstacleDistance(Number(e.target.value))} className="w-full accent-cyan-500"/><div className="mt-3 flex items-center justify-between text-[10px] text-slate-500"><span>Speed</span><div className="flex gap-1">{[0.5,1,2].map(s=><button key={s} onClick={()=>setSpeedMultiplier(s)} aria-pressed={state.speedMultiplier===s} className={`rounded px-2 py-1 font-mono ${state.speedMultiplier===s?'bg-cyan-500 text-white':'bg-slate-100 dark:bg-slate-900'}`}>{s}×</button>)}</div></div></div></aside>
      <main className={`${panel} min-w-0 overflow-hidden`}><div className="flex items-center justify-between border-b px-3 py-2.5 dark:border-slate-800"><div className="flex items-center gap-2 text-xs font-black"><Layers3 className="h-4 w-4 text-cyan-500"/>3D viewport</div><span className="font-mono text-[10px] text-slate-500">LIVE · {state.speedMultiplier}×</span></div><div className="p-2 sm:p-3"><ThreeSimulatorCanvas heightClass="h-[430px] sm:h-[520px] lg:h-[560px] xl:h-[620px]" showToolbar/></div><div className="grid grid-cols-2 sm:grid-cols-4">{[['LED',state.leds['13']?.on?'ON':'OFF'],['SERVO',`${state.servos.servo_01?.angle??90}°`],['ROVER',state.robot.status],['SONAR',`${state.obstacle.distanceToRobot} cm`]].map(([l,v])=><div key={l} className="border-t bg-white px-3 py-2 dark:border-slate-800 dark:bg-slate-950"><p className="text-[9px] font-black text-slate-500">{l}</p><p className="truncate text-xs font-bold">{v}</p></div>)}</div></main>
      <aside className={`${panel} min-w-0 overflow-hidden`} aria-label="Firmware editor"><div className="flex items-center justify-between border-b px-3 py-2.5 dark:border-slate-800"><div className="flex items-center gap-2 text-xs font-black"><Terminal className="h-4 w-4 text-cyan-500"/>Firmware editor</div><span className="font-mono text-[10px] text-slate-500">C++ / Arduino</span></div><div className="p-2"><MonacoEditorPanel key={preset} initialCode={code} language="cpp" targetBoard="Arduino Uno" height="520px"/></div></aside>
    </div><section className={`${panel} mt-4 overflow-hidden`}><button onClick={()=>setConsoleOpen(v=>!v)} className="flex min-h-11 w-full items-center justify-between px-3 text-left" aria-expanded={consoleOpen}><span className="flex items-center gap-2 text-xs font-black"><Terminal className="h-4 w-4 text-cyan-500"/>Serial console & events</span><span className="text-[10px] text-slate-500">{consoleOpen?'Collapse':`${state.serialLogs.length} events`}</span></button>{consoleOpen&&<div className="max-h-48 overflow-auto border-t bg-slate-950 px-3 py-2 font-mono text-[10px] dark:border-slate-800">{state.serialLogs.slice(-40).map((log,i)=><div key={`${log.timestamp}-${i}`} className={`py-1 ${log.type==='error'?'text-rose-400':log.type==='info'?'text-cyan-300':'text-slate-300'}`}>{log.text}</div>)}</div>}</section>
  </div></section>;
};
